# Generated by Django 2.0.2 on 2018-03-04 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number.', regex='^[0-9]{10}$'), django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
