# Generated by Django 2.0.2 on 2018-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180306_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='HOME-TOWN', max_length=128),
        ),
    ]
