# Generated by Django 2.0.2 on 2018-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180306_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_login',
            field=models.BooleanField(default=True),
        ),
    ]
