# Generated by Django 2.0.2 on 2018-03-08 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.IntegerField()),
                ('container_no', models.CharField(max_length=32)),
                ('vessel_name', models.CharField(max_length=32)),
                ('pod', models.CharField(max_length=32)),
                ('pol', models.CharField(max_length=32)),
                ('shipping_bill_no', models.CharField(max_length=32)),
                ('shipment_desc', models.CharField(max_length=128)),
                ('seal_no', models.CharField(max_length=32)),
                ('gross_weight', models.CharField(max_length=64)),
                ('net_weight', models.CharField(max_length=64)),
                ('no_of_cartons', models.IntegerField()),
                ('package_type', models.CharField(max_length=64)),
                ('hscode', models.IntegerField()),
                ('move_type', models.CharField(choices=[('CY', 'CY')], default='CY', max_length=3)),
                ('freight', models.CharField(choices=[('Prepaid', 'prepaid'), ('Collect', 'Collect')], default='prepaid', max_length=3)),
                ('discharge_type', models.CharField(choices=[('FCL', 'FCL')], default='FCL', max_length=3)),
                ('shipper_addr', models.CharField(max_length=256)),
                ('shipper_country', models.CharField(max_length=256)),
                ('shipper_cust_id', models.CharField(max_length=64)),
                ('freight_addr', models.CharField(max_length=256)),
                ('freight_country', models.CharField(max_length=256)),
                ('freight_cust_id', models.CharField(max_length=64)),
                ('consign_addr', models.CharField(max_length=256)),
                ('consign_country', models.CharField(max_length=256)),
                ('consign_cust_id', models.CharField(max_length=64)),
                ('notify1_addr', models.CharField(max_length=256)),
                ('notify1_country', models.CharField(max_length=256)),
                ('notify1_cust_id', models.CharField(max_length=64)),
                ('notify2_addr', models.CharField(max_length=256)),
                ('notify2_country', models.CharField(max_length=256)),
                ('notify2_cust_id', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
