# Generated by Django 2.0.2 on 2018-03-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='discharge_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='move_type',
        ),
    ]
