# Generated by Django 2.0.2 on 2018-03-08 09:41

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20180308_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discharge_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='FCL', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='freight',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Prepaid', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='CY', max_length=100, no_check_for_status=True),
        ),
    ]
