# Generated by Django 2.0.2 on 2018-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180403_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='container_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
