# Generated by Django 2.0.2 on 2018-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20180404_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discharge_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='freight',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
