# Generated by Django 2.0.2 on 2018-04-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20180404_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
