# Generated by Django 2.0.2 on 2018-04-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20180409_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(blank=True, max_length=32, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=64, null=True)),
                ('net_weight', models.CharField(blank=True, max_length=64, null=True)),
                ('no_of_cartons', models.IntegerField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('booking_no',)},
        ),
        migrations.AddField(
            model_name='container',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_booking', to='bookings.Booking'),
        ),
    ]
