# Generated by Django 2.0.2 on 2018-04-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20180424_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='container_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_cartons',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package_type',
        ),
    ]
